# Generated by Django 2.2.5 on 2020-03-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdaygifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='recipient',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
