# Generated by Django 2.2.5 on 2020-03-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdaygifts', '0002_gift_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='img',
            field=models.ImageField(default='corey.jpg', upload_to=''),
        ),
    ]
