# Generated by Django 2.2.5 on 2020-03-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdaygifts', '0003_gift_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='img',
            field=models.ImageField(default='corey.jpg', upload_to='bdaygifts-pics'),
        ),
    ]
