# Generated by Django 2.2.5 on 2020-03-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdaygifts', '0005_auto_20200323_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='img',
            field=models.ImageField(default='corey.jpg', upload_to='bdaygifts-pics'),
        ),
    ]
