# Generated by Django 2.2.5 on 2020-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdaygifts', '0007_gift_hover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='recipient',
            field=models.CharField(choices=[('tim', 'Tim'), ('karen', 'Karen')], default='None', max_length=20),
        ),
    ]
