# Generated by Django 2.2.5 on 2020-03-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdaygifts', '0008_auto_20200324_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='recipient',
            field=models.CharField(choices=[('Tim', 'Tim'), ('Karen', 'Karen')], default='None', max_length=20),
        ),
    ]
