# Generated by Django 2.2.5 on 2020-02-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('french', 'French'), ('english', 'English'), ('farsi', 'Farsi')], default='english', help_text='Book Language', max_length=1),
        ),
    ]
